- .eslintrc.json
eslint setting, react/react-in-jsx-scope 업데이트
> :wrench: update eslint setting

- .eslintrc.json
- src/pages/Home.tsx
- src/state/state.ts
.eslintrc.json
```
roles:{
...
"import/no-unresolved": "off",
"react/no-unknown-property": ["error", { "ignore": ["css"] }],
}
```
> :wrench: update eslint

- src/components/IngredientBadge.tsx
- src/styles/theme.ts
- src/types/styled.d.ts
IngredientBadge 컴포넌트 마크업 & 스타일링
> :lipstick: create IngredientBadge component

- src/components/IngredientButton.tsx
- src/components/IntredientButtonList.tsx
> :art: markup & styling  IngredientButtonList

- src/components/CombinationRankingCard.tsx
- src/components/IngredientBadge.tsx
- src/components/SandwitchBadgeList.tsx
- src/components/SandwitchInfo.tsx
- src/components/SandwitchInfoCard.tsx
SandwitchInfoCard 하위 컴포넌트 props로 넘겨받은 데이터로 렌더링하도록 연결
> :sparkles: connect SandwitchInfoCard children component props data

- src/components/CombinationRankingCard.tsx
- src/pages/Home.tsx
- src/styles/global.ts
CombinationRankingCard에서 SandwitchBadgeList 넘겨준 props로 렌더링 연결
> :sparkles: connect CombinationRankingCard & SandwitchBadgeList props data

- src/components/CombinationIngredientList.tsx
- src/components/CombinationRankingCard.tsx
- src/components/IngredientCard.tsx
- src/components/IngredientCardList.tsx
- src/pages/Home.tsx
> :lipstick: add IngredientCardList

- src/components/Header.tsx
- src/components/HeaderItemsWrap.tsx
- src/components/IngredientCardList.tsx
- src/components/SandwitchBadgeList.tsx
- src/layouts/RootLayout.tsx
- src/pages/BestCombinationPick.tsx
- src/pages/CustomCombination.tsx
- src/pages/Home.tsx
- src/pages/RandomResult.tsx
- src/pages/index.tsx
- src/router.tsx
- src/types/ISandwitch.ts
> :sparkles: add common types & page route

- src/components/HeaderItemsWrap.tsx
- src/router.tsx
- src/styles/global.ts
- 임시로 지정해둔 NavLink to path 값 수정
> :memo: Modify Router Path Link

- src/components/CombinationIngredientList.tsx
- src/pages/BestCombinationDetail.tsx
- src/pages/BestCombinationList.tsx
- src/pages/BestCombinationPick.tsx
BestCombinationPick 페이지 마크업 & 스타일링 1차 구현
> :lipstick: BestCombinationPick Page markup & styling

- src/components/CombinationIngredientList.tsx
- src/pages/BestCombinationDetail.tsx
> :bug: fix parameter error

- src/components/CombinationIngredientList.tsx
- src/pages/BestCombinationDetail.tsx
- tsconfig.json
- CombinationIngredientList 수정
- tsconfig compilerOptions 추가
"downlevelIteration": true 
iteration destructing 목적
> :lipstick: update CombinationIngredientList

- src/App.tsx
- src/components/CombinationRankingCard.tsx
- src/components/HeaderItemsWrap.tsx
- src/components/Like.tsx
- src/router.tsx
- webpack.config.js
- Router 경로 수정
- Webpack outpu publicPath: '/' 추가
```js
output: {
path: path.resolve(__dirname, 'dist'),
publicPath: '/',
clean: true,
},
```
- Like 버튼 수정
> :bug: solve nested routes path problem

- src/components/CombinationIngredientList.tsx
- src/components/CombinationRankingCard.tsx
- src/components/CommentInputWrap.tsx
- src/components/CommentItem.tsx
- src/components/Header.tsx
- src/components/HeaderItemsWrap.tsx
- src/components/IngredientCardList.tsx
- src/components/Like.tsx
- src/components/SandwitchInfoCard.tsx
- src/components/UI/RandomModalResult.tsx
- src/components/UI/Wrapper.tsx
- src/layouts/RootLayout.tsx
- src/pages/BestCombinationDetail.tsx
- src/pages/BestCombinationList.tsx
- src/pages/BestCombinationPick.tsx
- src/pages/CustomCombination.tsx
- src/pages/Home.tsx
- src/pages/Login.tsx
- src/pages/MyPage.tsx
- src/pages/RandomPick.tsx
- src/pages/Ranking.tsx
- src/styles/global.ts
> :lipstick: trim all page style

- .env.dev
- .gitignore
- node_modules/.package-lock.json
- package-lock.json
- package.json
- src/firebase.config.ts
- src/pages/BestCombinationDetailPage.tsx
- src/pages/LoginPage.tsx
- webpack.config.js
> :sparkles: add firebase OAuth

- .env.dev
- .gitignore
- node_modules/.package-lock.json
- package-lock.json
- package.json
- src/firebase.config.ts
- src/pages/BestCombinationDetailPage.tsx
- src/pages/LoginPage.tsx
- webpack.config.js
- Firebase 연동
- Firebase google OAuth
> ✨ add Firebase

- .env.dev
- src/components/IngredientButtonList.tsx
- src/components/UI/Button/IngredientButton.tsx
- src/pages/BestCombinationPickPage.tsx
꿀조합 선택 페이지 필터버튼 토글 기능 및 최대선택개수 초과 시 경고창 기능 추가
> ✨ add toggle filter & alert exceed maxSelctedNum

- src/pages/BestCombinationDetailPage.tsx
> :pencil2: modify hot_chilli image path

- src/types/ISandwitch.ts
인터페이스 수정 
(전) 
export interface 샌드위치뱃지리스트 {
맛: string[];
메인재료: string;
추가사항: string[];
}
(후)
export interface 샌드위치뱃지리스트 {
맛: string[];
메인재료: string[];
추가사항: string[];
}
> :pencil2: 인터페이스_재료 수정

- src/data/ingredients.json
재료 데이터 의 메인재료 에 아보카도 가 누락되어 추가
> :pencil2: 메인재료에 누락된 아보카도 추가

- src/components/CombinationRankingCard.tsx
- src/components/SandwitchBadgeList.tsx
- src/pages/RankingPage.tsx
:twisted_rightwards_arrows: 메인재료 타입 오류 병합
> :bug: 메인재료 타입 변경에 따른 타입 오류 수정

- src/pages/BestCombinationListPage.tsx
- src/pages/BestCombinationPickPage.tsx
"꿀 조합 보러가기" 버튼 클릭시 꿀 조합 리스트 페이지로 이동하면서 filter State 전달
> :sparkles: click button to navigate BestCombinationListPage

- src/pages/BestCombinationPickPage.tsx
최대 수 초과 시 선택되어있는 버튼을 눌러도 초과 alert이 뜨는 오류 수정
> :bug: fix maximum number exceeded error

- src/pages/BestCombinationPickPage.tsx
재료 필터 이미 선택된 필터일 시 선택 해제 기능 추가
> :bug: fix toggle  "재료"_filter

- src/pages/BestCombinationPickPage.tsx
> Feature/toggle best combination filter #3

- public/data/꿀조합/bestCombination.json
- src/App.tsx
- src/components/CommentItem.tsx
- src/components/Comments/CommentList.tsx
- src/firebase.config.ts
- src/pages/BestCombinationDetailPage.tsx
> :sparkles: comment리스트 view 완료

- src/styles/global.ts
> :lipstick: add global img no draggable

- node_modules/.bin/ansi-html
- src/App.tsx
- src/layouts/HeaderItemsWrap.tsx
- src/pages/LoginPage.tsx
- src/pages/MyPagePage.tsx
- src/utils/getOAuthProvider.ts
- 로그인 여부 확인 후 redirect 처리
- 로그아웃 기능 추가
> :sparkles: 로그인 redirect 처리 : 헤더, 로그인, 마이페이지, 로그아웃 기능 추가 

- src/api/addNewComment.ts
- src/components/Comments/CommentInputWrap.tsx
- src/pages/MyPagePage.tsx
> :sparkles: firebase 댓글 추가 완료

- src/types/ISandwich.ts
꿀조합 의 토스팅 유무 타입 boolean -> string 로 변경
> :pencil2: 꿀조합 의 토스팅 유무 타입 boolean -> string 로 변경

- src/hooks/useInfiniteScroll.ts
- src/pages/BestCombinationListPage.tsx
IntersectionObserver API를 활용한 무한스크롤 custom hook 생성
서버요청 방법에 따라 세부로직 수정 필요
> :sparkles: add custom_hook for Infinite_Scroll

- src/components/Common/Button/Top.tsx
- src/hooks/useScrollTop.ts
- src/layouts/RootLayout.tsx
- src/pages/BestCombinationListPage.tsx
- tsconfig.json
- webpack.config.js
Top 버튼 마크업 및 스타일링
Top 버튼 클릭 시 스크롤 상단으로 이동
> ✨ add custom_hook for Scroll_Top

- src/App.tsx
- src/api/addNewComment.ts
> :sparkles: 댓글리스트 불러오기

- src/constants/constants.ts
> 🚚 move initFilter constants.ts & change name from "initFilter" to "꿀조합_픽_초기_필터"

- public/data/ingredients.json
- src/firebase.config.ts
- src/hooks/useGetComments.ts
- src/pages/BestCombinationDetailPage.tsx
- src/utils/getFirebaseImgaURL.ts
- Firebase 꿀조합 정보 가져오기
- Firebase 이미지 데이터 가져오기
> ✨ Feature/best_combination_page get Firebase Data

- src/components/Comments/CommentItem.tsx
- src/hooks/useGetComments.ts
- src/types/IComment.ts
- src/utils/getTimePassedBy.ts
- src/utils/index.ts
- src/utils/setFirebaseImgaURL.ts
- 댓글 쓴 시간 기준으로 작성일 표시 
ex) ~ 초 전, ~분 전, ~시간 전, ~일 전, ~주 전, ~년 전
> ✨ Feature/get comment time by create time

- src/api/dbPush.ts
- src/hooks/useGetComments.ts
> :sparkles: Firebase dbPush

- src/api/dbGet.ts
- src/api/dbPush.ts
- src/components/Comments/CommentInputWrap.tsx
- src/components/Comments/CommentsContainer.tsx
- src/components/Common/Cards/SandwichInfoCard.tsx
- src/layouts/RootLayout.tsx
- src/pages/LoginPage.tsx
- src/state/index.ts
- 댓글 입력창 UI 다듬기
- 댓글 추가 후 입력창 초기화 기능 추가
> ♻️  refactor Comment input Wrap UI , add feature initialize Comment input when it done

- src/api/addNewComment.ts
- src/components/Comments/CommentItem.tsx
- src/components/Comments/CommentList.tsx
- src/components/Comments/CommentsContainer.tsx
- src/components/Ingredient/IngredientCard.tsx
- src/components/Ingredient/IngredientCardList.tsx
- src/hooks/useGetComments.ts
- src/pages/BestCombinationDetailPage.tsx
- src/typings/IComment.ts
- 꿀조합 상세 페이지 PC 디테일
- 댓글 시간 순서 내림차순으로 sorting
> :sparkles: Comments ordering

- src/components/BestCombinationList/BestCombinationList.tsx
- src/components/Common/Cards/SandwichInfoCard.tsx
- src/pages/BestCombinationDetailPage.tsx
- src/state/user.ts
> :pencil2: modify userLike-state

- src/components/Roulette/RandomRoulette.tsx
- src/pages/RandomPickPage.tsx
> :lipstick: 단찌 배치

- src/App.tsx
- src/api/dbSet.ts
- src/api/dbUpdate.ts
- src/components/BestCombinationList/BestCombinationList.tsx
- src/components/Common/Cards/SandwichInfoCard.tsx
- src/components/Ranking/CombinationRankingCard.tsx
- src/components/Roulette/RandomRoulette.tsx
- src/hooks/useInfiniteScroll.ts
- src/pages/RandomPickPage.tsx
- src/pages/RankingPage.tsx
- src/utils/getOAuthProvider.ts
> :memo: Build like structure

- src/components/CustomCombination/CombinationRegistration.tsx
- src/components/CustomCombination/CustomPageWrap.tsx
- src/components/CustomCombination/MyCombinationCard.tsx
- src/utils/customCombination/postCustom.ts
- 나만의 조합 등록 버튼 클릭시 제목 없을경우 발생하는 오류 수정
- pc 버전에서 레이아웃 틀어지는 부분 수정
> :bug: 나만의 조합 등록 버튼 클릭시 제목 없을경우 발생하는 오류 수정

- src/components/Common/Button/Top.tsx
> :recycle: modify Top-Button Position

- src/components/UI/Modal.tsx
> :lipstick: add Modal_Component styling for mobile

- src/App.tsx
- src/pages/MyPagePage.tsx
- myPage 사용자가 좋아요한 데이터 받아와 좋아요 개수 순으로 리스팅하기
> :memo: mypage 데이터 좋아요순 정렬 완료

- src/components/BestCombinationAttribute/AttributeButton.tsx
- src/components/BestCombinationList/NotFoundBestCombinationList.tsx
- src/components/BestCombinationPick/NavigateListPageButton.tsx
- src/components/Common/Cards/SandwichInfoCard.tsx
- src/components/UI/Modal.tsx
- 꿀조합 Pick&List 페이지 버튼 hover 시 스타일링 추가
> :lipstick: add styling when hover button on Pick&List_Page

- src/components/BestCombinationAttribute/AttributeButton.tsx
- src/components/BestCombinationPick/IngredientButtonListContainer.tsx
- src/components/BestCombinationPick/NavigateListPageButton.tsx
- src/pages/BestCombinationPickPage.tsx
> :lipstick: add styling when hover button on Pick&List_Page_#2

- src/pages/MyPagePage.tsx
- 마이페이지 카드에 삭제기능 구현
- 기존 변수에 담았던 데이터를 상태 관리로 변경 리팩토링
> :sparkles: 삭제버튼 기능 구현 및 상태 리팩토링

- src/components/BestCombinationList/BestCombinationList.tsx
- src/components/BestCombinationPick/IngredientButtonListContainer.tsx
- src/components/BestCombinationPick/NavigateListPageButton.tsx
- src/pages/BestCombinationPickPage.tsx
- src/utils/changeAttrToQueryString.ts
- Pick 페이지에서 속성 선택 쿼리스트링으로 List페이지 이동
- 필터링 기능 로컬로 임시 연결
> ♻️ add Attribute as QueryString

- node_modules/.package-lock.json
- package-lock.json
- package.json
- src/components/CustomCombination/CustomPageModal.tsx
- src/components/CustomCombination/CustomPageWrap.tsx
- src/hooks/useCheckLogin.ts
- 로그인 없이 뒤로 가기 또는 주소 입력으로 커스텀 페이지에 접근 시 modal을 이용해 로그인 안내 후 로그인 페이지로 이동
- 새로 고침 및 뒤로 가기 시에 데이터 초기 화 경고를 통해 실수로 데이터 초기화되는 실수를 방지
(뒤로 가기의 경우 커스텀 모달을 사용하였는데 새로고침의 경우 커스텀 모달을 사용할 수 없어 뒤로 가기 와 새로고침의 UI 가 다른 부분에 대하여 고민 후 추후 수정 예정)
> :recycle: 로그인 없이 커스텀 페이지 접속시 로그인 페이지로 이동 새로고침 및 뒤로가기 시 데이터 초기화 경고

- src/api/dbUpdate.ts
- src/components/BestCombinationDetail/Header.tsx
- src/components/BestCombinationList/BestCombinationList.tsx
- src/components/Comments/CommentItem.tsx
- src/components/Ingredient/IngredientCardList.tsx
- src/constants/constants.ts
- src/hooks/useComments.ts
- src/pages/BestCombinationDetailPage.tsx
- src/typings/ISandwich.ts
> :recycle: refacoring remove type any

- src/components/BestCombinationAttribute/AttributeButtonList.tsx
- src/components/BestCombinationPick/IngredientButtonListContainer.tsx
- src/hooks/useToggleFilter.ts
- src/pages/BestCombinationPickPage.tsx
- Pick페이지 최대 선택 개수 초과시 모달창에서 빨간 텍스트로 변경
> :recycle: modify from modal to text_color_red when maxSelectedAttr_Error

- src/components/Ingredient/IngredientCardList.tsx
> :sparkles: ingredientCard scroll

- src/App.tsx
- src/api/getFilteredBestCombination.ts
- src/components/BestCombinationList/BestCombinationList.tsx
- src/components/Common/Button/LikeRed.tsx
- src/components/Common/Cards/SandwichInfoCard.tsx
- src/components/Common/SandwichInfo.tsx
- src/hooks/useCheckLogin.ts
- src/pages/BestCombinationListPage.tsx
- 꿀조합 리스트 get 요청 로직 api로 분리
- 리스트페이지 렌더링 최적화
> :recycle: Refactoring for ListPage rendering optimization

- src/services/Firebase/Auth/getOAuthProvider.ts
> :ambulance: initialize like when user login

- src/hooks/useLikedBestCombination.ts
- 좋아요 버튼 클릭 시 서버-클라이언트 동기화 오류 핫픽스
> 🚑 Sync LikeList When Clicked like_button

- src/components/Comments/CommentInputWrap.tsx
- src/components/Comments/CommentsContainer.tsx
- src/components/Ingredient/IngredientCardList.tsx
- src/components/Ranking/RankingTab.tsx
- src/hooks/useComments.ts
- src/hooks/useInfiniteScroll.ts
- src/styles/theme.ts
- 댓글 추가 시 무한스크롤 적용이 안되는 에러 해결
- 댓글 창 위치 수정
> :bug: solve comments iniginity scroll

- src/components/Comments/CommentInputWrap.tsx
> :pencil2: 오타수정

- src/components/BestCombinationDetail/Header.tsx
- src/components/CustomCombination/Ingredient.tsx
디테일 페이지 헤딩 태그 수정 및 스타일 선택자 수정
(접근성 개선 목적)
> ✏️ 디테일 페이지 헤딩 태그 수정 및 스타일 선택자 수정

- src/components/BestCombinationPick/AttributePick.tsx
- src/components/BestCombinationPick/DeskTopImage.tsx
- src/pages/BestCombinationPickPage.tsx
> ♻️ Refactoring for PickPage rendering optimization #2

- src/api/getBestCombination.ts
- src/api/getBestCombinationList.ts
- src/components/BestCombinationDetail/Contents.tsx
- src/components/BestCombinationDetail/Header.tsx
- src/components/Comments/CommentInputWrap.tsx
- src/components/Comments/CommentItem.tsx
- src/pages/BestCombinationDetailPage.tsx
- src/pages/MyPagePage.tsx
- 디테일 페이지 컨텐츠 영역 컴포넌트 최적화
- 댓글 카드 컴포넌트 최적화
- 디테일 페이지 firebase api 로직 분리
> :recycle: optimize detail page

- node_modules/.package-lock.json
- package-lock.json
- package.json
- src/layouts/Header.tsx
- src/state/isLoggedIn.ts
recoil-persist 라이브러리를 활용하여 sessionStorage에 로그인 여부 정보 저장
> :sparkles: memoize login status in sessionStorage using recoil-persist

- public/index.html
폰트를 불러오는 link 태그에 preload 를 사용하여 랜더링 차단 시간  단축
> :recycle: 폰트를 불러오는 link 태그에 preload 를 사용하여 랜더링 차단 시간  단축

- node_modules/.package-lock.json
- package-lock.json
- package.json
- src/hooks/useScrollTop.ts
> :recycle: add debounce at scroll event

- public/index.html
- src/components/BestCombinationPick/NavigateListPageButton.tsx
- src/components/Common/SandwichInfo.tsx
- src/components/Common/UI/Button.tsx
- src/components/CustomCombination/CombinationRegistration.tsx
- src/components/CustomCombination/Ingredient.tsx
- src/components/CustomCombination/MyCombinationCard.tsx
- src/components/CustomCombination/NextStepButton.tsx
- src/components/Ranking/CombinationRankingCard.tsx
- src/pages/MyPagePage.tsx
- src/pages/RandomPickPage.tsx
- src/styles/common.ts
- src/styles/theme.ts
- src/typings/styled.d.ts
- 접근성 향상(색상 대비)을 위한 Color 추가
- SandwichInfo 이미지 로딩으로 인한 레이아웃 쉬프트 문제 해결을 위한 min-height 설정 추가
- 유저만의 조합 전체 조합이 불러와졌다가 사라지는 에러를 위해 초기화 로직 추가
> Feature/optimization #5

- node_modules/.package-lock.json
- package-lock.json
- package.json
- src/hooks/useScrollTop.ts
- lodash 라이브러리에서 lodash-es로 변경 (ESM으로 export 됐고 더 작은 번들 사이즈 제공으로 변경)
- useScrollTop파일 lodash-es 사용 부분 tree_shaking으로 최적화
> ♻️ modify from lodash to lodash-es for tree_shaking

- src/styles/global.ts
> :lipstick: remove highlights from  mobile touch

- src/components/BestCombinationList/BestCombinationList.tsx
- src/components/Common/LoadingSpinner.tsx
- src/components/Common/SandwichInfo.tsx
- src/components/Ranking/RankingList.tsx
- Loading Spinner 컴포넌트화
- 꿀조합리스트 페이지 데이터패칭 시 로딩 스피너 추가
- 꿀조합 카드 모바일 화면에서 레이아웃 쉬프트 방지용 min-height 추가
> Feature/page best combination list #5

- src/components/Roulette/RandomRoulette.tsx
- src/pages/RandomPickPage.tsx
> :lipstick: fix roulette button

- src/components/MyPage/MyPageTab.tsx
- src/components/Roulette/RandomRoulette.tsx
random의 숫자가 변경될 때 모달창이 띄워지는 로직에서 random 숫자가 겹칠시 이벤트가 발생하지 않았던 오류 수정
> Feature/fixroulette #2

- src/components/BestCombinationList/BestCombinationList.tsx
- src/components/Common/LoadingSpinner.tsx
- src/components/Ranking/RankingList.tsx
- 로딩 스피너 위치 조정
- 기존 translate에서 translate3d로 변경 (gpu 사용으로 성능 향상 이점)
> :lipstick: modify loading_spinner position

- src/layouts/Header.tsx
> :pencil2: 헤더 의 로고 위치 수정

- src/components/CustomCombination/CustomPageWrap.tsx
- src/components/CustomCombination/MyCombinationStep.tsx
MyCombinationStep 과 CustomPageWrap의 의존성을 낮춰 반복적인 리랜더 개선
> :recycle:  MyCombinationStep 과 CustomPageWrap 의 의존성을 낮춰 반복적인 리랜더 개선

- .eslintrc.json
- src/components/Comments/CommentInputWrap.tsx
- src/components/Comments/CommentItem.tsx
- src/pages/BestCombinationDetailPage.tsx
- 댓글 띄어쓰기 기능 추가 및 이벤트 변경(submit -> keydown, click)
- 댓글 입력창 포커스 색 변경
- 댓글 입력창 label 추가
- 게시 버튼 크기 수정
> :recycle: update comment for usability

- src/components/MyPage/MyPageContainer.tsx
- src/pages/MyPagePage.tsx
> :recycle: myPagePage refactoring

- node_modules/.package-lock.json
- package-lock.json
- src/components/CustomCombination/Ingredient.tsx
- src/components/CustomCombination/MyCombinationCard.tsx
- src/components/CustomCombination/SelectCombination.tsx
- src/styles/global.ts
- 커스텀 페이지 재료 선택 탭으로 접근 가능하게 수정 
- 각 선택 카테고리 별 스크린리더용 설명 텍스트 추가
> :bug: 커스텀 페이지 재료 선택 탭으로 접근 가능하게 수정 각 선택 카테고리 별 스크린 리더용 설명 텍스트 추가

- src/components/MyPage/MyPageContainer.tsx
- src/components/MyPage/MyPageTab.tsx
- src/components/Ranking/RankingTab.tsx
[MyPage] '좋아요한 꿀조합' 리스트 내의 디테일 페이지에서  뒤로가기 클릭시 '유저만의 꿀조합'으로 가는 오류를 탭에 따른 경로 지정으로 해결
> :bug: fix back space error on tab buttons

- src/components/MyPage/MyPageList.tsx
- src/components/MyPage/MyPageTab.tsx
이전 탭별 경로 수정으로 인해 틀어진 리스트 수정 및 ui 관련 오타 수정
> Feature/refactoring my page#3

- src/components/MyPage/MyPageList.tsx
> :pencil2: fix list

- webpack/webpack.config.prod.js
> :pencil2: add favicon_webpack_CopyPlugin

- public/index.html
> :pencil2: add favicon_link_tag

- public/index.html
> :pencil2: delete icon_link_tag

- src/components/Roulette/RandomRoulette.tsx
> :memo: add keyboard event
